name: CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Run Unit & Integration Tests in Parallel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-type: [unit, integration]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run ${{ matrix.test-type }} tests
        run: npm run test:${{ matrix.test-type }}

  e2e:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4

  sast:
    name: Static Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ESLint Security Plugin
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

  sca:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Run npm audit
        run: npm audit --audit-level=high
