name: Deploy to Vercel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Rollup
        run: npm install rollup --legacy-peer-deps

      - name: Install SWC Dependencies
        run: npm install @swc/core @swc/cli --legacy-peer-deps

      - name: Rebuild Native Modules
        run: npm rebuild

      - name: Build Project
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
