name: Security Scanning

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  schedule:
    - cron: "0 0 * * 0" # Run weekly

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write # Required for security scanning tools

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false # Prevents using the default GITHUB_TOKEN, forcing a PAT if needed

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      # Static Application Security Testing (SAST)
      - name: Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      # Dependency Scanning (SCA)
      - name: Audit Dependencies
        run: npm audit --audit-level=high
        continue-on-error: true

      # Using Snyk for more comprehensive scanning
      - name: Set up Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check for vulnerabilities
        run: snyk test --severity-threshold=high || echo "Vulnerabilities found"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
